{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipsec.serviceAccountName" . }}
  labels:
{{ include "ipsec.labels" . | nindent 4 }}
{{- end -}}
