{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "avcmp.serviceAccountName" . }}
  labels:
{{ include "avcmp.labels" . | nindent 4 }}
{{- end -}}
