{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipsec_service.serviceAccountName" . }}
  labels:
{{ include "ipsec_service.labels" . | nindent 4 }}
{{- end -}}
